### ISSUE TITLE
[Documentation] Create a ROADMAP.md 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#144]
### [Documentation] Create a ROADMAP.md 

Process:
- [x]  Create 1st draft w/ outline > https://hackmd.io/s9LEh-CpRXKEOWbrFw36uA
- [x]  Prioritize high level goals
- [x]  Peer review of 1st draft 
- [x]  Update draft to edit content 
- [x]  Peer review of 2nd draft
- [x]  Update draft to be ready to publish
- [x]  Publish on GitHub/develop as ROADMAP.md
- [ ] Tag 1 or more people to peer review

**Comment by agentpoyo** [comment]
LGTM :+1:
