### ISSUE TITLE
[Process] Proof of concept: add tab completion 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#265]
### [Process] add tab completion 

**Short description:**
- to help test developers implement new tests faster and with fewer typing issues, implement support for tab completion
- improves developer process when implementing a new conformance test that has a large number of characters, like "volume_hostpath_not_found" in #159 

**Tasks:** 
- [ ] update process
- [ ] update documentation
- [ ]  TBD

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Reviewer Approved` column
   - [x] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by williscool** [comment]
https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial

**Comment by lixuna** [comment]
@williscool @nupejosh Is the A/C that worked as expected from https://github.com/cncf/cnf-conformance/blob/5b14e5f4ab15b24807172a099bf9bd73387a18bf/USAGE.md#install-tab-completion ?

**Comment by nupejosh** [comment]
@lixuna yes I used the usage docs that you pasted above, as well as the comment thread here in [PR 361](https://github.com/cncf/cnf-conformance/pull/361)

comments about results from A/C here in [PR 361](https://github.com/cncf/cnf-conformance/pull/361#issuecomment-681096767)
