### ISSUE TITLE
[Refactor] Improve output by refactoring all console messaging to use standard logging

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#280]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/280#issuecomment-647630612) 

# [Refactor] Improve output by refactoring all console messaging to use standard logging

**Short description:**
- refactor all output messages to use standard logging throughout code

Currently there is some messaging that is sent to the console (standard out) bypassing the logging functionality.  This means it is more difficult to show what is on the screen and it can become noise.  It also limits the ability to send the output to different places (eg. a log file or service)  

## TODO

**Tasks:**

- [x] Update all code providing developer log messages to use built-in logging functionality.
- [x] Update all code providing verbose end user messages to use custom verbose function and use verbose flagging to enable/disable
- [x] Choose appropriate logging and verbose level for "converted" code.
- [x] Set the default logging level for end-users (eg. info, fatal, debug) to be used by the binary
   - Does not create config.yml
   - No config.yml by default
   - What is the log level?  Is it set at compile or runtime?
- [x] Set the default logging level for end-users (eg. info, fatal, debug) building from source
   - Currently log level is set in [config.yml](https://github.com/cncf/cnf-conformance/blob/224c9e2f70ff3f46acec030a3c84cacb14c8d700/config.yml) which is checked into the repository
- [x] Update docs for contributing developers to the use of logging functions
- [x] Update docs for contributing developers to the use of verbose functions
- [x] Document how end users running tests can use verbose flag and what it does
- [x] Document how end users running tests can use set logging levels, what the defaults are and what they will show
- [x] DOCUMENT the precedence of setting logging level
   1. Cli flag is highest precedence
   2. Environment var is next level of precedence
   3. Config file is last level of precedence 
- [x] Spec tests covering setting different logging levels and overrides
- [x] Spec tests covering verbosity usage

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
DRAFT Acceptance Criteria: building on A/C from #159 
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed
- [ ]  USAGE md is updated, if needed
- [ ]  Installation instructions is updated, if needed

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests


### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### Update yml validator, if needed
- N/A

### When using the test `cnf-conformance volume_localstorage_not_found` command the sample "good" CNF should PASS test successfully:
- [ ] Run `./cnf-conformance setup`
- [ ] Run  `./cnf-conformance sample_coredns_setup`
- [ ] Run  `./cnf-conformance volume_localstorage_not_found`
- [ ] I expect to see the output and results from the test
- [ ] I expect to see PASSED for the test. Example:
         - [ ] "✔️ PASSED: local storage volumes not found [EMOJI]"

### When using the test `crystal spec --tag `volume_localstorage_not_found`` command the sample "good" CNF should PASS and the "bad example CNF"  should FAIL test:
- [ ] Run `crystal spec --tag volume_localstorage_not_found`
- [ ] I expect to see the output and results from the test
- [ ] I expect to see "✔️ PASSED: local storage volumes not found [EMOJI]
- [ ] I expect to see "❌ FAIL: local storage volumes found [EMOJI]"

### I would expect the CNF to pass when I run the entire test category suite (`statelessness`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance statelessness`
- [ ]  I expect to see the output and results from all tests in the test category
- [ ]  I expect to see PASSED for the test and test category 

### I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ] I can see a screenshot of the new test in the comments of this ticket

**Comment by taylor** [comment]
Level of effort estimate:


- @wavell 5
- @denverwilliams 5
- @lixuna 5
- @nupejosh 5
- @williscool 5
- @agentpoyo 5
- @taylor 5

**Comment by wavell** [comment]
Created a bug ticket for extra output (I don't think this is covered by this ticket) https://github.com/cncf/cnf-conformance/issues/307

**Comment by wavell** [comment]
### ./cnf-conformance all # with fatal in config.yml
![image](https://user-images.githubusercontent.com/29548/87592222-2032d480-c6af-11ea-90a8-c8b5ba501caa.png)
### ./cnf-conformance all -l info # with fatal in config.yml
![image](https://user-images.githubusercontent.com/29548/87592743-fcbc5980-c6af-11ea-9b8e-f47a3e2b0d68.png)
### ./cnf-conformance all -l info # with fatal in config.yml and error in ENV
![image](https://user-images.githubusercontent.com/29548/87594975-6be77d00-c6b3-11ea-88a6-0d27912390b6.png)
![image](https://user-images.githubusercontent.com/29548/87595836-caf9c180-c6b4-11ea-997b-a02a37f3fcf6.png)
### ./cnf-conformance all # with fatal in config.yml and unset error in ENV
![image](https://user-images.githubusercontent.com/29548/87597539-976c6680-c6b7-11ea-9727-c2a02bea3aea.png)
![image](https://user-images.githubusercontent.com/29548/87601201-36925d80-c6ba-11ea-9b7d-9f99df3f0628.png)

#With Logging level set to fatal and I pass the verbose CLI flag I would expect to see all normal end-user messaging and additional verbose output when I run the entire test suite (all)
## This one seems to not be working
![image](https://user-images.githubusercontent.com/29548/87601835-81f93b80-c6bb-11ea-8714-35ae9ada9de2.png)

## But works with -l
![image](https://user-images.githubusercontent.com/29548/87601923-aa813580-c6bb-11ea-927e-8d9c31fbc233.png)

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/88113658-d6972d80-cb77-11ea-93f6-b7b796ead509.png)
