### ISSUE TITLE
[Refactor]  Update how and when results are saved so a repeated warning for overwriting results.yml does not occur

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#282]
[Acceptance Criteria DRAFT](https://github.com/cncf/cnf-conformance/issues/282#issuecomment-648390045) 

# [Refactor]  Update how and when results are saved so a repeated warning for overwriting results.yml does not occur

**Short description:**
- Currently the results.yml file is created in multiple steps which causes a warning message prompt to be shown about overwriting the file. 
    - Message “Do you want to overwrite results.yml? (y/n)”

## TODO

**Tasks:**

TBD

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance Criteria: copy of https://github.com/cncf/cnf-conformance/issues/280, needs updated
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed
- [ ]  USAGE md is updated, if needed
- [ ]  Installation instructions is updated, if needed

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests


### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- N/A

### Update yml validator, if needed
- N/A


### With Logging level set to `info` in the config.yml I would expect to see INFO level messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the INFO messages in the output
- [ ]  I expect to see PASSED for the test


### With Logging level set to `fatal` in the config.yml I would expect to only see "normal" end user messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to only  see "normal" end user messages in the output
- [ ]  I expect to see PASSED for the test


### When the logging level set to `fatal` and I set the environment variable for logging level to INFO I should see INFO messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output to show logging information for INFO logging level
- [ ]  I expect to see PASSED for the test

### When the logging level set to `fatal`, and the environment logging level to ERROR, and I pass the log level CLI flag for INFO I should see INFO messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output to show logging information for INFO logging level
- [ ]  I expect to see PASSED for the test

### When the logging level set to `fatal` and I pass the log level CLI flag for INFO I should see INFO messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output to show logging information for INFO logging level
- [ ]  I expect to see PASSED for the test

### With Logging level set to `fatal` and I do NOT pass the verbose CLI flag I would expect to see only end-user messaging for PASSED, FAILED, Final score and similar when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### With Logging level set to `fatal` and I pass the verbose CLI flag I would expect to see all normal end-user messaging and additional verbose output when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ] I can see a screenshot of the new test in the comments of this ticket

**Comment by lixuna** [comment]
Level of effort in pts: 01,2,3,5,8,13, 21pts:
---

**Comment by agentpoyo** [comment]
I followed all the steps in the Acceptance Criteria. Looks good.

**Comment by taylor** [comment]
@denverwilliams / @wavell / @agentpoyo please add screenshots re: https://github.com/cncf/cnf-conformance/issues/282#issuecomment-648390045

Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ]  I can see a screenshot of the new test in the comments of this ticket

**Comment by agentpoyo** [comment]
###  I should not see repeated warnings about overwriting results.yml when I run the `setup` command twice
- [x]  Follow common steps above 
- [x] Remove any leftover results.yml, by running `rm -f results.yml`
- [x] Run `./cnf-conformance setup` once
- [x] I do not expect to a warnings about overwriting results.yml
- [x] Run `./cnf-conformance setup` a second time
- [x] I do not expect to a warnings about overwriting results.yml

![282_1](https://user-images.githubusercontent.com/14348948/87338701-2ee08680-c50b-11ea-8819-ec3cf609b61b.png)

###  I should not see repeated warnings about overwriting results.yml when I run the `cnf_setup` command
- [x] I have completed the common steps above 
- [x] I have already run `setup`
- [x]  Run `./cnf-conformance cnf_setup cnf-config=./example-cnfs/coredns/cnf-conformance.yml`
- [x] I do not expect to a warnings about overwriting results.yml

![282_2](https://user-images.githubusercontent.com/14348948/87338737-3dc73900-c50b-11ea-815f-7cebfe7199c2.png)

###  I should not see repeated warnings about overwriting results.yml when I run the `all` command
- [x] I have completed the common steps above 
- [x] I have already run `setup`
- [x] I have already run the `cnf_setup` command with a valid config file
- [x]  Run  `./cnf-conformance all`
- [x] I do not expect to a warnings about overwriting results.yml
- [x]  I expect to see PASSED for the test

![282_3](https://user-images.githubusercontent.com/14348948/87338783-50417280-c50b-11ea-81a6-9f1b7219928d.png)

Currently my chaosmesh test seems to fail and the cnf-conformance never exits.

![282_4](https://user-images.githubusercontent.com/14348948/87338885-723af500-c50b-11ea-9dd8-0af8bc61d5df.png)

**Comment by taylor** [comment]
@wavell, @denverwilliams, do we need to open a new ticket to deal with the chaosmesh test failures?  Is this known/expected?
