### ISSUE TITLE
[enhancement] Update `all` command to call the initialize function if needed

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#283]
[Acceptance Criteria DRAFT](https://github.com/cncf/cnf-conformance/issues/283#issuecomment-648412642) 

# [enhancement] Update `all` command to call the initialize function if needed

**Short description:**
- The `all` command requires running `setup` (initialization) before running.  Would be nice if it happens automatically

## TODO

**Tasks:**

TBD

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed
- [ ]  USAGE md is updated, if needed
- [ ]  Installation instructions is updated, if needed

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ] Run `shards install`
- [ ] Run `crystal build  src/cnf-conformance.cr`
- [ ] I expect to have a executable `cnf-conformance` binary
   - Running `ls -l cnf-conformance` should show cnf-conformance with `x` bits sit (eg. `-rwxrwxr-x`)

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- N/A

### Update yml validator, if needed
- N/A


###  When I should not see repeated warnings about overwriting results.yml when I run the minimal CNF Developer steps for testing a CNF
- [ ]  Follow common steps above 
- [ ] Remove any leftover results.yml, by running `rm -f results.yml`
- [ ]  Run  `./cnf-conformance all cnf-config=./example-cnfs/coredns/cnf-conformance.yml`
- [ ] I do not expect to see any errors about setup or initialization
- [ ]  I expect to see PASSED for the test


### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ] I can see a screenshot of the new test in the comments of this ticket

**Comment by lixuna** [comment]
closing as invalid, issue is handled by #290
