### ISSUE TITLE
[Feature] Add version command

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#284]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/284#issuecomment-648428305) 

# [Feature] Add version command

**Short description:**
- Add a version command which shows the semantic version of the running binary

## TODO

**Planning:**

- [x] Implementation discussion
- [x] Acceptance Criteria: how will it be tested?
- [x] Level of effort in points

**Tasks:**

TBD

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [x] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
### _DRAFT TBD_ Acceptance Criteria for peer review:   
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed
- [ ]  USAGE md is updated, if needed
- [ ]  Installation instructions is updated, if needed

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ] Run `shards install`
- [ ] Run `crystal build  src/cnf-conformance.cr`
- [ ] I expect to have a executable `cnf-conformance` binary
   - Running `ls -l cnf-conformance` should show cnf-conformance with `x` bits sit (eg. `-rwxrwxr-x`)

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- N/A

### Update yml validator, if needed
- N/A


DRAFT TBD
###  I should see the [ADD_CORRECT_VERSION_HERE] when building a binary from source and running the version command
- [ ]  Follow common steps above 
- [ ] Run `./cnf-conformance version`
- [ ]  I expect to see to see the correct semantic release version

DRAFT TBD
###  I should see the semantic version matching a tagged binary release when I run the version command
- [ ]  Download the binary release...
- [ ] Run `./cnf-conformance version`
- [ ]  I expect to see to see the correct semantic release version


### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ] I can see a screenshot of the new test in the comments of this ticket

**Comment by williscool** [comment]
likely just a file similar to

https://github.com/rails/rails/blob/master/version.rb

**Comment by lixuna** [comment]
planning A/C will resume after implementation is decided.

**Comment by lixuna** [comment]
Level of effort in points: 0,1,2,3,5,8,13,21:
---

**Comment by williscool** [comment]
@wavell @denverwilliams  so currently on our releases i.e.

https://github.com/cncf/cnf-conformance/releases/tag/v0.7.1-beta1

we are only tarballing the the source not the actual binary. 

I wonder if https://github.com/cncf/cnf-conformance/pull/305 won't be necessary if we don't tarball the bin

**Comment by williscool** [comment]
we should also documet the `test_version` branch behavior

**Comment by williscool** [comment]
im also kind of reticent about creating releases everytime the test suite is run

**Comment by thewolfpack** [comment]
We definitely do not need a new release, especially a new patch release for
every CI build.

Ideally we could add some tag/flag to a PR to indicate we want a release
created.

**Comment by williscool** [comment]
ah I meant the about in the specs 

https://github.com/cncf/cnf-conformance/blob/master/spec/utils/release_manager_spec.cr

in the current version a relase is created and deleted in all of the tests

**Comment by williscool** [comment]
tested in travis things seem good. one thing I noticed though was if upsert_release is run a second time
you get this error from github

```
I, [2020-07-15 05:40:08 UTC #1637]  INFO -- cnf-conformance: asset: {"message" => "Validation Failed", "request_id" => "91CC:08BB:201CB:2760A:5F0E96B8", "documentation_url" => "https://developer.github.com/v3", "errors" => [{"resource" => "ReleaseAsset", "code" => "already_exists", "field" => "name"}]}
[32mCreated a release for: HEAD-24b7c63[0m
```

but I think its only an issue if a release already exists for a commit

**Comment by wavell** [comment]
> tested in travis things seem good. one thing I noticed though was if upsert_release is run a second time
> you get this error from github
> 
> ```
> I, [2020-07-15 05:40:08 UTC #1637]  INFO -- cnf-conformance: asset: {"message" => "Validation Failed", "request_id" => "91CC:08BB:201CB:2760A:5F0E96B8", "documentation_url" => "https://developer.github.com/v3", "errors" => [{"resource" => "ReleaseAsset", "code" => "already_exists", "field" => "name"}]}
> [32mCreated a release for: HEAD-24b7c63[0m
> ```
> 
> but I think its only an issue if a release already exists for a commit

Should we move this to approved?

**Comment by williscool** [comment]
@wavell the only reason i held off was that we are gzipping the bin instead of it just being raw

but I can fix that in #306  so yeah I'll approve

**Comment by lixuna** [comment]
@williscool @wavell 

1. please mark off the acceptance criteria steps that were used to QA this issue in https://github.com/cncf/cnf-conformance/issues/284#issuecomment-648428305

2. please add the requested screenshots to a new comment in this ticket to show that the feature is working as expected.

**Comment by williscool** [comment]
non-tagged release version cmd screenshot

![image](https://user-images.githubusercontent.com/394931/88142944-5f3bbb00-cbc4-11ea-90e3-e0befb2ae9fe.png)

**Comment by williscool** [comment]
@wavell just noticed something  about version command re the AC for this ticket


or maybe im not thinking about it the right way...
only branch builds are created through travis ... so all of the version commands would only ever say the master-COMMIT_HASH style of name.
we would have to explicity run a build on a tag to get the version to build with that tag name.
is that how we want it?


(this is a bump from slack discucssion ) 

https://vulk.slack.com/archives/GTSL40B47/p1595401067080000

**Comment by wavell** [comment]
> @wavell just noticed something about version command re the AC for this ticket
> 
> or maybe im not thinking about it the right way...
> only branch builds are created through travis ... so all of the version commands would only ever say the master-COMMIT_HASH style of name.
> we would have to explicity run a build on a tag to get the version to build with that tag name.
> is that how we want it?
> 
> (this is a bump from slack discucssion )
> 
> https://vulk.slack.com/archives/GTSL40B47/p1595401067080000

@williscool yes.  see automated release portion in https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view
