### ISSUE TITLE
[Install] Add curl install option

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#301]
### [Install] Add curl install option

**Short description:**
- Improve binary install: curl command for installing
- Helps people start to run test quicker
- installable shell script, that can be `curl`-ed and piped to /bin/sh

**Tasks:** 
- [ ] update process
- [ ] update documentation
- [ ]  TBD

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
DRAFT Acceptance Criteria:  (based on https://github.com/cncf/cnf-conformance/issues/280#issuecomment-647630612)
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed
- [ ]  USAGE md is updated, if needed
- [ ]  Installation instructions is updated, if needed

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests


### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- N/A

### Update yml validator, if needed
- N/A


### With Logging level set to `info` in the config.yml I would expect to see INFO level messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the INFO messages in the output
- [ ]  I expect to see PASSED for the test


### With Logging level set to `fatal` in the config.yml I would expect to only see "normal" end user messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to only  see "normal" end user messages in the output
- [ ]  I expect to see PASSED for the test


### When the logging level set to `fatal` and I set the environment variable for logging level to INFO I should see INFO messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output to show logging information for INFO logging level
- [ ]  I expect to see PASSED for the test

### When the logging level set to `fatal`, and the environment logging level to ERROR, and I pass the log level CLI flag for INFO I should see INFO messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output to show logging information for INFO logging level
- [ ]  I expect to see PASSED for the test

### When the logging level set to `fatal` and I pass the log level CLI flag for INFO I should see INFO messages when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output to show logging information for INFO logging level
- [ ]  I expect to see PASSED for the test

### With Logging level set to `fatal` and I do NOT pass the verbose CLI flag I would expect to see only end-user messaging for PASSED, FAILED, Final score and similar when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### With Logging level set to `fatal` and I pass the verbose CLI flag I would expect to see all normal end-user messaging and additional verbose output when I run the entire test suite (`all`)
- [ ]  Follow common steps above
- [ ]  Run  `./cnf-conformance sample_coredns_setup`
- [ ]  Run  `./cnf-conformance all`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ] I can see a screenshot of the new test in the comments of this ticket

**Comment by taylor** [comment]
MVP features determined 2020-07-09
- Script will be written in bash
- Where do we put the executable? => home
- Keep everything self-contained => in user “home directory”
- Automatically write PATH to shell user configuration file that’s independent of primary file (Eg. .bash-cnf-conformance) which is 
- What shells do we support for setting PATH? => Bash and Zsh
- What do we do if we do not recognize the users shell?
- Output error (ex. Shell unknown)
- Don’t write any shell configuration
- Message saying, please set your PATH
- Getting things working after install
- Tell the user they can restart the session
- Tell the user how to manually load into existing shell
- OPTIONAL Timeboxed: try to support automatically load the configuration for them in the existing shell
- Have test coverage for the installer => yes
- Have test coverage for using installer via curl => yes
- Install which version?	Dynamically download latest “stable” release from https://github.com/cncf/cnf-conformance/releases

**Comment by taylor** [comment]
Level of effort in points (0,1,2,3,5,8,13,21): **5**


- @nupejosh 3
- @denverwilliams 3
- @williscool 5
- @wavell 5
- @taylor 5
- @agentpoyo 5

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/89232187-90e15880-d5ac-11ea-9a04-1b45f6d755d5.png)
![image](https://user-images.githubusercontent.com/29548/89232515-2ed52300-d5ad-11ea-8aa1-20bc0c344621.png)

![image](https://user-images.githubusercontent.com/29548/89232427-0ea56400-d5ad-11ea-9536-e887edec3edc.png)

![image](https://user-images.githubusercontent.com/29548/89232828-f4b85100-d5ad-11ea-859c-4ba7610e613a.png)

![image](https://user-images.githubusercontent.com/29548/89233589-85dbf780-d5af-11ea-992a-a62f23ddfcf1.png)

![image](https://user-images.githubusercontent.com/29548/89233847-1fa3a480-d5b0-11ea-835d-52f95f51465e.png)

couldn't install any shells on the pair box 
![image](https://user-images.githubusercontent.com/29548/89233908-4eba1600-d5b0-11ea-9cdb-76b3a40be54d.png)

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/89333947-626e8680-d65b-11ea-8317-807264161e13.png)
