### ISSUE TITLE
[Feature] Automated Release Manager

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#306]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/306#issuecomment-658310888) 

Related: #284 

# [Feature] Automated Release Manager based on Automated Version Generator

**Short description:**
- Upload semantic version of the running binary
- Upload md5 hash of binary in release notes template
- Upload semantic version of the source code in tar.gz format **update: it looks like the prerelease process does this automatically**
- Upload semantic version of the source code in zip format **update: it looks like the prerelease process does this automatically**
- Insert issue titles from all commits in generated release into release notes template

## TODO

**Planning:**

- [ ] Implementation discussion
- [ ] Acceptance Criteria: how will it be tested?
- [ ] Level of effort in points

**Tasks:**

TBD

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by wavell** [comment]
### Acceptance Criteria for peer review:   
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed https://github.com/cncf/cnf-conformance/blob/master/CONTRIBUTING.md
- [ ]  USAGE md is updated, if needed  https://github.com/cncf/cnf-conformance/blob/master/USAGE.md
- [ ]  Installation instructions is updated, if needed https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md
- [x]  Release instructions are updated https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view (related to #107 )


###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ] Run `shards install`
- [ ] Run `crystal build  src/cnf-conformance.cr`
- [ ] Run `crystal build  src/cnf-conformance.cr` to create an executable `cnf-conformance` binary
- [ ] Run `./cnf-conformance setup` to initialize the test suite and install prereqs

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- N/A

### Update yml validator, if needed
- N/A

### When I follow the process to create a new tagged release using Travis CI a new draft release will be created on Github 
- [ ] I have source code which is passing all spec tests
- [ ] I follow the documentation for creating a new release using the automated Travis CI process
- [ ] I expect to see a Travis CI pipeline for the tagged release
- [ ] I should see the drafted "pre-release" https://github.com/cncf/cnf-conformance/releases with the semantic version of the binary
- [ ] I should see the drafted "pre-release" https://github.com/cncf/cnf-conformance/releases, with the md5 hash of binary in release notes template
- [ ] I should see the drafted "pre-release" https://github.com/cncf/cnf-conformance/releases, with the semantic version of the source code in tar.gz format
- [ ] I should see the drafted "pre-release" https://github.com/cncf/cnf-conformance/releases, with the semantic version of the source code in zip format
- [ ] I should see the drafted "pre-release" https://github.com/cncf/cnf-conformance/releases, with the issue numbers and titles from all commits in the release notes template

### Screenshots in the comments
- [ ] I can see a screenshot of the new tagged published release in the comments of this ticket
- [ ] I can see a screenshot showing version command with published release
- [ ] I can see a screenshot with a source non-tagged version command usage

**Comment by wavell** [comment]
**update: it looks like the prerelease process includes the source automatically**

**Comment by williscool** [comment]
> **update: it looks like the prerelease process includes the source automatically**

so I noticed this myself... after I had already written the code lol

**Comment by nupejosh** [comment]
I can see a screenshot showing version command with published release
 I can see a screenshot with a source non-tagged version command usage

![Screen Shot 2020-08-06 at 5 14 38 PM](https://user-images.githubusercontent.com/3164983/89588084-8cb17700-d808-11ea-8fae-6b6ca121eeb6.png)

I can see a screenshot of the new tagged published release in the comments of this ticket

<img width="923" alt="Screen Shot 2020-08-06 at 5 15 01 PM" src="https://user-images.githubusercontent.com/3164983/89588085-8d4a0d80-d808-11ea-9b86-86cbce57678e.png">
