### ISSUE TITLE
[Maintenance] Update to latest stable version of Crystal lang 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#311]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/311#issuecomment-661284622)

[Maintenance] Update to latest stable version of Crystal lang 
---

**Short description:**
- Update to latest stable version of Crystal lang 

## TODO

**Planning:**

- [ ] Implementation discussion
- [ ] Acceptance Criteria: how will it be tested?
- [ ] Level of effort in points

**Tasks:**

- [ ] Test the latest release v0.35.1
- [ ] Document Crystal dependencies which do not build with newer versions
- [ ] Document if the dependencies work with a earlier version of Crystal
- [ ] Document if there are suggested alternative libraries

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Reviewer Approved` column
   - [x] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
### Acceptance Criteria for peer review:   
--
### Documentation is updated:
- [ ]  Documentation for Contributors is updated, if needed https://github.com/cncf/cnf-conformance/blob/master/CONTRIBUTING.md
- [ ]  USAGE md is updated, if needed  https://github.com/cncf/cnf-conformance/blob/master/USAGE.md
- [ ]  Installation instructions is updated, if needed https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md
- [ ]  Release instructions are updated https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view (related to #107 )


###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]  As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ] Run `shards install`
- [ ] Run `crystal build  src/cnf-conformance.cr`
- [ ] Run `crystal build  src/cnf-conformance.cr` to create an executable `cnf-conformance` binary
- [ ] Run `./cnf-conformance setup` to initialize the test suite and install prereqs

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- N/A

### Update yml validator, if needed
- N/A

### When I run the version command using a downloaded published binary release, I should see the matching semantic version printed
- [ ]  Download the binary release from https://github.com/cncf/cnf-conformance/releases
- [ ] Take note of the semantic version from Github
- [ ] Run `./cnf-conformance version`
- [ ]  I expect to see to see the matching semantic release version printed matching the Github release

### When I follow the process to create a new tagged release using Travis CI a new draft release will be created on Github 
- [ ] I have source code which is passing all spec tests
- [ ] I follow the documentation for creating a new release using the automated Travis CI process
- [ ] I expect to see a Travis CI pipeline for the tagged release
- [ ] I should see the drafted "pre-release" https://github.com/cncf/cnf-conformance/releases, if the Travis CI build passes

### I should not see a drafted pre-release if the spec tests fail in Travis CI
- [ ] I follow the documentation for creating a new release using the automated Travis CI process with source code that fails to pass spec tests
- [ ] I expect to see a Travis CI pipeline running spec tests
- [ ] I do not expect to see a drafted "pre-release" https://github.com/cncf/cnf-conformance/releases


###  I should see the something indicating the binary is a non-tagged release (eg. commit, branch name, timestamp, or some combination) when building a binary from source on a non-tagged branch (eg. master) and running the version command
- Note: this is after using source, eg. clone repo
- [ ]  Follow common steps above 
- [ ]  Run `./cnf-conformance version`
- [ ]  I expect to see to something showing it's not a tagged release


### Screenshots in the comments
- [ ] I can see a screenshot of the new tagged published release in the comments of this ticket
- [ ] I can see a screenshot showing version command with published release
- [ ] I can see a screenshot with a source non-tagged version command usage

**Comment by taylor** [comment]
pair@cnfdev03:~/workspace/taylor$ crystal  -v
Crystal 0.33.0 [612825a53] (2020-02-14)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by lixuna** [comment]
Level of effort in pts: 0,1,2,3,5,8,13,21 = 8 pts
---

@wavell 8
@denverwilliams 8
@williscool 8
@nupejosh 5
@agentpoyo 8
@taylor 5
@lixuna 5

**Comment by taylor** [comment]
Tasks:

- [ ]  Test the latest release v0.35.1
- [ ]  Document Crystal dependencies which do not build with newer versions
- [ ]  Document if the dependencies work with a earlier version of Crystal
- [ ]  Document if there are suggested alternative libraries

**Comment by williscool** [comment]
Release notes are VERY useful for this

https://github.com/crystal-lang/crystal/releases

**Comment by lixuna** [comment]
@nupejosh did the steps pass in the A/C? Can you please mark the checkboxes that have been verified in the A/C and provide a screenshot of the expected result?

**Comment by nupejosh** [comment]
![Screen Shot 2020-08-26 at 2 14 39 PM](https://user-images.githubusercontent.com/3164983/91346554-a1997e80-e7a6-11ea-8fe6-807c85f70027.png)

**Comment by nupejosh** [comment]
This first screenshot shows all specs passing except for one, however this was an intermittent failure because of a timing issue. The second screenshot shows that exact failing spec passing when ran independently.. all tests pass. 

![Screen Shot 2020-08-26 at 4 05 16 PM](https://user-images.githubusercontent.com/3164983/91356940-11fbcc00-e7b6-11ea-9d75-ec09512bf233.png)

![Screen Shot 2020-08-26 at 4 05 25 PM](https://user-images.githubusercontent.com/3164983/91357126-5c7d4880-e7b6-11ea-9d2b-2d1be38753dc.png)

**Comment by lixuna** [comment]
@nupejosh That's awesome thanks! I'm happy we were able to update to the Latest release 0.35.1 from 19 June 2020.
