### ISSUE TITLE
[Documentation] Create slides to show running all of the CNF Conformance tests crystal src/cnf-conformance.cr all

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#60]
[Acceptance Criteria] 

### [Documentation] Create slides to show running all of the CNF Conformance tests 

Short description: 
- to create example slides to show screenshots of running all tests (as of Feb 26)

EPIC: CNF Conformance Test Suite

Release: v0.0.1

Test Category: all

Type of test (static or runtime) = both

---

### Tasks:

- [x]  follow steps in https://github.com/cncf/cnf-conformance/blob/master/USAGE.md
- [x]  run 
```
crystal src/cnf-conformance.cr all
```
- [x]  capture screen grabs of process
- [x]  create slide deck
- [x]  add images to slides

**Comment by lixuna** [comment]
These tasks were done to prepare for the CNTT Virtual Event presentation
https://docs.google.com/presentation/d/1qmVl6pLoXDqSF94A9rS749UwH8bNfVQ4b12bWXH8sOs/edit#slide=id.g7ebb418dca_0_183
